#!/usr/bin/env tsx
/**
 * Pre-compute anchor embeddings for PolicyRouter
 * 
 * This script generates embeddings for anchor texts used in semantic routing.
 * Run once to generate embeddings, which are then committed to the repo.
 * 
 * Usage:
 *   npm run precompute-anchors
 * 
 * Requirements:
 *   - COPILOT_API_KEY environment variable must be set
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const COPILOT_PROXY_URL = 'https://copilot.s-x.workers.dev/v1';
const EMBEDDING_MODEL = 'text-embedding-3-small';

interface AnchorText {
  label: string;
  text: string;
  modelClass: string;
}

interface AnchorEmbedding {
  label: string;
  modelClass: string;
  embedding: number[];
}

const defaultAnchorTexts: AnchorText[] = [
  {
    label: 'fast_simple_query',
    text: 'What is 2+2?',
    modelClass: 'fast',
  },
  {
    label: 'balanced_query',
    text: 'Explain the difference between machine learning and deep learning in a few sentences.',
    modelClass: 'balanced',
  },
  {
    label: 'complex_quality_query',
    text: 'Provide a comprehensive analysis of the economic impacts of climate change on developing nations, including specific case studies and policy recommendations.',
    modelClass: 'quality',
  },
];

async function getEmbedding(text: string, apiKey: string): Promise<number[]> {
  const response = await fetch(`${COPILOT_PROXY_URL}/embeddings`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: EMBEDDING_MODEL,
      input: [text],
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(
      `Embedding API error: ${response.status} ${response.statusText}\n${errorText}`
    );
  }

  const data = await response.json();
  return data.data[0].embedding;
}

async function precomputeAnchors() {
  const apiKey = process.env.COPILOT_API_KEY;
  
  if (!apiKey) {
    console.error('❌ Error: COPILOT_API_KEY environment variable is required');
    console.error('\nSet it in your shell or .env file:');
    console.error('  export COPILOT_API_KEY="your-key-here"');
    process.exit(1);
  }

  console.log('🔄 Pre-computing anchor embeddings...\n');

  const anchors: AnchorEmbedding[] = [];

  for (const anchor of defaultAnchorTexts) {
    console.log(`Computing embedding for: ${anchor.label}`);
    try {
      const embedding = await getEmbedding(anchor.text, apiKey);
      anchors.push({
        label: anchor.label,
        modelClass: anchor.modelClass,
        embedding,
      });
      console.log(`  ✓ ${embedding.length} dimensions\n`);
    } catch (error) {
      console.error(`  ✗ Failed for ${anchor.label}:`, error);
      process.exit(1);
    }
  }

  // Write to TypeScript file
  const outputPath = path.join(
    __dirname,
    '../src/services/policyRouter/precomputedAnchors.ts'
  );
  
  const tsContent = `/**
 * Pre-computed anchor embeddings for PolicyRouter
 * 
 * Generated by: npm run precompute-anchors
 * Generated at: ${new Date().toISOString()}
 * Model: ${EMBEDDING_MODEL}
 * 
 * DO NOT EDIT MANUALLY - regenerate with: npm run precompute-anchors
 */

import { AnchorEmbedding, ModelClass } from './index';

export const PRECOMPUTED_ANCHORS: AnchorEmbedding[] = ${JSON.stringify(anchors, null, 2).replace(/"fast"/g, 'ModelClass.FAST').replace(/"balanced"/g, 'ModelClass.BALANCED').replace(/"quality"/g, 'ModelClass.QUALITY')};
`;

  fs.writeFileSync(outputPath, tsContent);
  
  console.log('✅ Pre-computed anchors saved to:');
  console.log(`   ${outputPath}\n`);
  console.log(`📊 Summary:`);
  console.log(`   Anchors computed: ${anchors.length}`);
  console.log(`   Embedding dimensions: ${anchors[0]?.embedding.length || 0}`);
  console.log(`   Model: ${EMBEDDING_MODEL}\n`);
  console.log('💡 Next steps:');
  console.log('   1. Review the generated file');
  console.log('   2. Commit it to your repository');
  console.log('   3. The worker will now use these pre-computed embeddings');
}

precomputeAnchors().catch((error) => {
  console.error('❌ Fatal error:', error);
  process.exit(1);
});
